name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      docker_images:
        description: "Create docker images"
        required: false
        default: "true"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build Windows
        run: |
          dotnet publish SourceApi/Server -r win-x64 --self-contained false --configuration Release

      - name: Build Linux
        run: |
          dotnet publish SourceApi/Server -r linux-x64 --self-contained false --configuration Release

      - name: Run Unit-Tests
        run: |
          dotnet test SourceApi --no-build
          dotnet test ErrorCalculatorApi
          dotnet test RefMeterApi
          dotnet test SerialPortProxy

      - name: Start Service for Acceptance Tests
        run: |
          cd SourceApi/Server/bin/Release/net7.0/linux-x64/publish
          ./WebSamDeviceApis&
          echo "SOURCE_MOCK_PID=$!" >> $GITHUB_ENV

      - name: Exit Service
        run: |
          kill -9 $SOURCE_MOCK_PID

      - name: Upload Build Artifacts Windows
        uses: actions/upload-artifact@v3
        with:
          name: build-win-x64
          path: "SourceApi/Server/bin/Release/net7.0/win-x64/publish/"
          if-no-files-found: error
          retention-days: 1

      - name: Upload Build Artifacts Linux
        uses: actions/upload-artifact@v3
        with:
          name: build-linux-x64
          path: "SourceApi/Server/bin/Release/net7.0/linux-x64/publish/"
          if-no-files-found: error
          retention-days: 1

      - name: Docker build
        if: github.event.inputs.docker_images == 'true'
        run: |
          docker build . -f SourceApi/Server/Dockerfile -t=device-api
          docker save -o device-api.tar device-api

      - name: Upload Docker Artifacts
        if: github.event.inputs.docker_images == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: device-api
          path: device-api.tar
